### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by Jorgeruiz97** [RangerDigital/senko#2]
Hello is there any plan to publish this to PyPi?
In my ideal iot development I would love to Install Senko with upip:

```python
# main.py

import upip
upip.install('micropython-senko')
```

I would love to contribute to this!
Congrats this is a great project! and it actually works!

**Comment by RangerDigital** [comment]
Thank You, Great idea! I will look into that.

**Comment by RangerDigital** [comment]
🥳 Done! if you have any issue with `micropython-senko` feel free to open a new issue!

**Comment by Jorgeruiz97** [comment]
Amazing! @RangerDigital thank you!
