### ISSUE TITLE
https://gitlab.com/

### ISSUE THREAD

**Issue by pcshetty** [RangerDigital/senko#3]
Hi, 

Thanks for this easy to use lib for OTA updates. 

I was testing this lib to check if I can use this to pull repo from https://gitlab.com/  and I get this error when I try.  
 
NotImplementedError: Redirects not yet supported 

-----
OTA = senko.Senko(user="myusername", repo="myreponame", url="https://gitlab.com", working_dir="app2", files=["main.py"])
OTA.update()
-----
(  this error is coming from the urequests.py lib)
Any idea on how to fix this?
----

i tried this ( RAW) URL and it works fine.  

OTA = senko.Senko(user="netdevopstraining", repo="micropython_ota_test", url="https://gitlab.com/netdevopstraining/micropython_ota_test/-/raw/main/app2",   files=["main.py"])

----

Also wanted to check if this lib will work with private repos.

Thanks 

Prathap

**Comment by RangerDigital** [comment]
Hi!

Thanks for reaching out, Senko was build with only GitHub in mind. :disappointed:

There are two ways to provide repository location:
1. Provide `user` and `repo` - This only works for GitHub.
2. Provide only `url` value - Values for `user`, `repo`, `branch`, `working_dir` are ignored in this case.

Senko currently doesn't support using private repositories, but I will look into that. 

If you have any more questions feel free to open another issue. :blush:

**Comment by pcshetty** [comment]
Thanks for the quick response
